# code: language=ansible

# ----------------------------
# Core tasks
# ----------------------------

- name: Ensure dirs exist
  ansible.builtin.file:
    path: "{{ composition_root }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"

- name: "Create Dockerfile"
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ composition_root }}/Dockerfile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0666"

- name: "Create compose file"
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ composition_root }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0666"

- name: "Create .env file"
  ansible.builtin.template:
    src: environment_vars.j2
    dest: "{{ composition_root }}/.environment_vars"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0666"

# ----------------------------
# Specific tasks
# ----------------------------

- name: "Template out config file"
  ansible.builtin.template:
    src: traefik-config.yaml.j2
    dest: "{{ composition_root }}/traefik.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0666"
  register: config_file

- name: "Create HomelabCA dir"
  ansible.builtin.file:
    dest: "{{ composition_root }}/HomelabCA"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: "Touch HomelabCA file"
  ansible.builtin.copy:
    content: ""
    dest: "{{ composition_root }}/HomelabCA/acme.json"
    force: false
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Check if conntainer is running
  community.docker.docker_container_info:
    name: "{{ composition_name }}"
  register: result

- name: Restart on configuration change
  community.docker.docker_compose_v2:
    project_src: "/opt/containers/{{ composition_name }}"
    state: restarted
  when: result.exists and config_file.changed
