---
# https://www.jeffgeerling.com/blog/2020/ansible-best-practices-using-project-local-collections-and-roles
roles:
  - name: geerlingguy.docker
  - name: geerlingguy.pip

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
