---
- name: Remove deprecated or insecure packages | package-01 - package-09
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  loop:
    - inetd
    - prelink
    - rsh-server
    - telnet-server
    - xinetd
    - ypserv

- name: Find cron files and directories
  ansible.builtin.find:
    paths:
      - /etc
    patterns:
      - cron.hourly
      - cron.daily
      - cron.weekly
      - cron.monthly
      - cron.d
      - crontab
    file_type: any
  register: cron_directories

- name: Ensure permissions on cron files and directories are configured
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: og-rwx
  with_items: "{{ cron_directories.files }}"

- name: Create limits.d-directory if it does not exist | sysctl-31a, sysctl-31b
  ansible.builtin.file:
    path: /etc/security/limits.d
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Create additional limits config file -> 10.hardcore.conf | sysctl-31a, sysctl-31b
  community.general.pam_limits:
    dest: /etc/security/limits.d/10.hardcore.conf
    domain: "*"
    limit_type: hard
    limit_item: core
    value: "0"
    comment: Prevent core dumps for all users. These are usually not needed and may contain sensitive information
  when: not ansible_check_mode # the directory needs to be created first, which does not happen in check_mode

- name: Set 10.hardcore.conf perms to 0400 and root ownership
  ansible.builtin.file:
    path: /etc/security/limits.d/10.hardcore.conf
    owner: root
    group: root
    mode: "0440"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Create coredump.conf.d-directory if it does not exist
  ansible.builtin.file:
    path: /etc/systemd/coredump.conf.d
    owner: root
    group: root
    mode: "0755"
    state: directory
  when: ansible_service_mgr == "systemd"

- name: Create custom.conf for disabling coredumps
  ansible.builtin.template:
    src: coredumps.conf.j2
    dest: /etc/systemd/coredump.conf.d/custom.conf
    owner: root
    group: root
    mode: "0644"
  when: ansible_service_mgr == "systemd"
  notify: Reload systemd

- name: Add pinerolo_profile.sh to profile.d
  ansible.builtin.template:
    src: pinerolo_profile.conf.j2
    dest: /etc/profile.d/pinerolo_profile.sh
    owner: root
    group: root
    mode: "0750"

- name: Add autologout to profile env
  ansible.builtin.template:
    src: tmout.sh.j2
    dest: /etc/profile.d/tmout.sh
    owner: root
    group: root
    mode: "0644"

- name: Protect sysctl.conf
  ansible.builtin.file:
    path: /etc/sysctl.conf
    owner: root
    group: root
    mode: "0440"
    state: touch
    modification_time: preserve
    access_time: preserve
