---
- name: Ensure installation dependencies exist
  ansible.builtin.apt:
    name: software-properties-common
    state: present

- name: Install Ansible
  ansible.builtin.apt:
    name: ansible
    state: present
