---
- name: Copy gpsd configuration file
  ansible.builtin.template:
    src: gpsd.j2
    dest: /etc/default/gpsd
    owner: root
    group: root
    mode: "0644"

- name: Enable the GPSd service
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - gpsd
