---

- name: Install required packages
  ansible.builtin.apt:
    name: python3-docker
    state: present

- name: Ensure composition roles are run
  ansible.builtin.include_role:
    name: "container_{{ item }}"
  vars:
    composition_name: "{{ item }}"
    composition_root: "/opt/containers/{{ item }}"
  loop: "{{ compositions }}"
  when: compositions

# - name: Ensure all composition containers are started
#   community.docker.docker_compose_v2:
#     project_src: "/opt/containers/{{ item }}"
#     state: restarted
#   loop: "{{ compositions }}"
#   when: compositions
