---
# DNS + Time server

- name: DNS + Time server
  hosts: host-casio
  become: true
  pre_tasks:
    - name: Define containers to configure
      ansible.builtin.set_fact:
        compositions:
          - adguardhome
          - adguardhome-sync
          - traefik

  roles:
    - role: common_bootstrap
    - role: common_rpi_hardware
    - role: common_security
    - role: geerlingguy.docker
    - role: role_node_exporter
    - role: role_containers
    - role: role_ntp_server
  handlers:
    - name: Reboot host
      ansible.builtin.reboot:
