---
# DNS + Time server

- name: DNS + Time server
  hosts: host-sekio
  become: true
  pre_tasks:
    - name: Define containers to configure
      ansible.builtin.set_fact:
        compositions:
          - adguardhome
          - traefik

  roles:
    - role: common_bootstrap
    - role: common_rpi_hardware
    - role: common_security
    - role: geerlingguy.docker
    - role: role_ansible_pull
    - role: role_containers
  handlers:
    - name: Reboot host
      ansible.builtin.reboot:
